Add importing and exporting of persistence
Zilliqa/Zilliqa pull request #2377
Opened 2020-12-03 03:08 UTC by KaustubhShamshery

## Description

Add an API called `ExportPersistence` for exporting persistence

Add bootstrap option --path for choosing a tar file from where to load persistence

## Backward Compatibility

- [ ] This is not a breaking change
- [ ] This is a breaking change

## Review Suggestion

## Status

### Implementation

- [ ] **ready for review**

### Integration Test (Core Team)

- [ ] local machine test

- [ ] small-scale cloud test

2020-12-04 04:23 UTC, bb111189 requested changes
1. sanitize input
2. disable such API by default. togglable by constants
3. avoid using system()

2020-12-20 05:14 UTC, bb111189 requested changes
Can we make the reinit api togglable? 

For instance, for public isolation, it should not be available. For private isolated like Ceres, it should be enabled.

2021-01-07 06:19 UTC, bb111189 approved these changes

2021-01-07 23:49 UTC, ansnunez approved these changes

2021-01-11 07:05 UTC, merged