Remove pending transaction pool
Zilliqa/Zilliqa pull request #2478
Opened 2021-03-19 11:17 UTC by ansnunez

## Description

This PR removes the pending transaction pool, which has already been replaced by the off-chain transaction status feature.

Changes are mostly on lookup side, involving removal of `m_pendingTxns` and `m_droppedTxns`, which lookup and seed nodes usually populate when receiving `PENDINGTXN` message from shards. `m_pendingTxnStore` - used by seed nodes for seed-to-seed syncing - has also been removed.

Shard side will continue to send `PENDINGTXNS` message in order for lookup nodes to populate the off-chain database. For this reason, shard side will also continue to use `m_unconfirmedTxns`.

`GetPendingTxn` and `GetPendingTxns` API are also removed.

For StatusServer, `IsTxnInMempool` continues to be available, but only for shard side.

## Backward Compatibility

- [ ] This is not a breaking change
- [ ] This is a breaking change

## Review Suggestion

## Status

### Implementation

- [ ] **ready for review**

### Integration Test (Core Team)

- [ ] local machine test

- [ ] small-scale cloud test

2021-03-19 11:24 UTC, ansnunez commented on src/libServer/LookupServer.h
> -  Json::Value GetPendingTxn(const std::string& tranID);
Todo: Reroute to `GetTransactionStatus`

2021-03-22 10:20 UTC, KaustubhShamshery approved these changes

2021-03-22 10:24 UTC, ansnunez commented on src/libServer/LookupServer.h
> -  Json::Value GetPendingTxns();
Todo: Reroute to remote DB query in separate PR

2021-03-22 15:34 UTC, sandipbhoir requested changes

2021-03-22 15:34 UTC, sandipbhoir commented on src/libLookup/Lookup.cpp
> -        // for each shard, send request for pending txn message to l2l data
Can rename `FetchMbTxPendingTxMessageFromL2l` to `FetchMBnForwardTxMessageFromL2l`?

2021-03-23 00:09 UTC, sandipbhoir approved these changes

2021-03-23 03:55 UTC, merged