fix processing of duplicate updates
Zilliqa/Zilliqa pull request #2527
Opened 2021-04-27 12:58 UTC by KaustubhShamshery

## Description
Also detach `BulkWrite`

## Backward Compatibility

- [ ] This is not a breaking change
- [ ] This is a breaking change

## Review Suggestion

## Status

### Implementation

- [ ] **ready for review**

### Integration Test (Core Team)

- [ ] local machine test

- [ ] small-scale cloud test

2021-04-27 13:20 UTC, sandipbhoir requested changes

2021-04-27 13:20 UTC, sandipbhoir commented on src/libNode/FinalBlockProcessing.cpp
> +    } else if (REMOTESTORAGE_DB_ENABLE && !ARCHIVAL_LOOKUP) {
Would be better to add LOOKUP_NODE_MODE in check as well ?

2021-04-28 06:28 UTC, ansnunez approved these changes

2021-04-28 07:05 UTC, sandipbhoir approved these changes

2021-04-28 07:35 UTC, merged