Make unix domain server timeout configurable
Zilliqa/Zilliqa pull request #2572
Opened 2021-05-24 16:57 UTC by KaustubhShamshery

## Description

## Backward Compatibility

- [ ] This is not a breaking change
- [ ] This is a breaking change

## Review Suggestion

## Status

### Implementation

- [ ] **ready for review**

### Integration Test (Core Team)

- [ ] local machine test

- [ ] small-scale cloud test

2021-05-24 17:33 UTC, bb111189 requested changes

2021-05-24 17:33 UTC, bb111189 commented on cmake/InstallJsonrpccpp.cmake
> +    URL https://github.com/KaustubhShamshery/libjson-rpc-cpp/archive/v1.2.0-time-patch.tar.gz
change to this repo https://github.com/Zilliqa/libjson-rpc-cpp

2021-05-25 01:09 UTC, sandipbhoir requested changes

2021-05-25 01:09 UTC, sandipbhoir commented on tests/Server/Test_ScillaIPCServer.cpp
> +  s.SetWaitTime(10);
May be we add wait time to constants.xml

2021-05-25 05:08 UTC, vaivaswatha commented
I see that you're calling `SetWaitTime()` at each place that `UnixDomainSocketServer` is instantiated. An alternate to this is to derive from `UnixDomainSocketServer`, a class that sets `SetWaitTime` in its constructor. That way you only create instances of this class and don't manually set the time everytime.

2021-05-25 05:13 UTC, sandipbhoir approved these changes

2021-05-25 05:15 UTC, bb111189 approved these changes

2021-05-25 05:17 UTC, KaustubhShamshery commented
> I see that you're calling `SetWaitTime()` at each place that `UnixDomainSocketServer` is instantiated. An alternate to this is to derive from `UnixDomainSocketServer`, a class that sets `SetWaitTime` in its constructor. That way you only create instances of this class and don't manually set the time everytime.

For now since only scilla server needs setting of this value and it is only intastiated once, the current design does not have any major disadvantage. However, the concern is valid, can be made a lower priority issue

2021-05-25 06:28 UTC, merged