Set limit on querying DS Block (To be tested)
Zilliqa/Zilliqa pull request #2593
Opened 2021-06-08 08:45 UTC by sunny-teo9000

## Description
To limit the amount of DS blocks being retrieved from ProcessGetDSBlockFromSeed
https://github.com/Zilliqa/Issues/issues/686

## Backward Compatibility

- [ ] This is not a breaking change
- [ ] This is a breaking change

## Review Suggestion

## Status

### Implementation

- [ ] **ready for review**

### Integration Test (Core Team)

- [ ] local machine test

- [ ] small-scale cloud test

2021-06-09 12:42 UTC, chetan-zilliqa commented on constants.xml
> +        <FETCH_DS_BLOCK_LIMIT>2</FETCH_DS_BLOCK_LIMIT>
Should this constant be in `seed` section ? P2PComm deals with the network layer.

2021-06-09 12:42 UTC, chetan-zilliqa commented on src/libLookup/Lookup.cpp
> +    if (diff > FETCH_DS_BLOCK_LIMIT) {
Do we think that we should increase the `FETCH_DS_BLOCK_LIMIT`?  As on the client-side, the getter function `FetchLatestDSBlocksSeed` is called in a loop, So there would be many calls for a large block range and every time lookup has to execute function for sliced block range.

2021-06-10 03:00 UTC, sandipbhoir requested changes

2021-06-10 03:53 UTC, chetan-zilliqa approved these changes

2021-06-10 03:59 UTC, sandipbhoir approved these changes

2021-06-10 07:17 UTC, merged