[master] Moveupdatetodisk after every N accounts of migration
Zilliqa/Zilliqa pull request #2698
Opened 2021-08-24 10:10 UTC by Kooriii

same as  #2691

## Description

## Backward Compatibility

- [x] This is not a breaking change
- [ ] This is a breaking change

## Review Suggestion

## Status

### Implementation

- [x] **ready for review**

### Integration Test (Core Team)

- [ ] local machine test

- [x] small-scale cloud test

2021-08-24 10:12 UTC, chetan-zilliqa approved these changes

2021-08-24 10:16 UTC, sandipbhoir approved these changes

2021-08-25 05:28 UTC, sunny-teo9000 requested changes

2021-08-25 05:28 UTC, sunny-teo9000 commented on src/libData/AccountData/AccountStore.cpp
> +      if (!MoveUpdatesToDisk()) {
Seems like build error is complaining about this part
https://app.travis-ci.com/github/Zilliqa/Zilliqa/builds/236072281

Maybe some commits should be merged before this?

2021-09-01 09:10 UTC, sunny-teo9000 approved these changes

2021-09-01 09:37 UTC, merged