[master] Remove NAT logic
Zilliqa/Zilliqa pull request #2718
Opened 2021-09-08 02:30 UTC by Kooriii

## Description
Remove NAT logic from repository as the current NAT logic does not work for the actual NAT-ed IP

## Backward Compatibility

- [x] This is not a breaking change
- [ ] This is a breaking change

## Review Suggestion

## Status

### Implementation

- [x] **ready for review**

### Integration Test (Core Team)

- [x] local machine test

- [ ] small-scale cloud test

2021-09-08 02:34 UTC, sunny-teo9000 approved these changes

2021-09-08 06:36 UTC, KaustubhShamshery approved these changes

2021-09-08 08:14 UTC, chetan-zilliqa commented
May be you can also remove the reference of `libNAT.so` from dockerfile.
https://github.com/Zilliqa/Zilliqa/blob/ad9bc74e2efa0a2150cafe2243ff7de7d4d22be9/docker/Dockerfile#L114

2021-09-08 08:15 UTC, chetan-zilliqa requested changes
Maybe you can also remove the reference of `libNAT.so` from the Zilliqa Dockerfile.
https://github.com/Zilliqa/Zilliqa/blob/ad9bc74e2efa0a2150cafe2243ff7de7d4d22be9/docker/Dockerfile#L114

2021-09-09 03:07 UTC, chetan-zilliqa approved these changes

2021-09-13 04:30 UTC, sandipbhoir approved these changes

2021-09-13 04:30 UTC, merged