Support fetching of Chain ID in fetchBlockchainInfo in Scilla IPC server
Zilliqa/Zilliqa pull request #2779
Opened 2022-02-09 08:54 UTC by Kooriii

## Description
Add support for fetching Chain ID in `fetchBlockchainInfo` in `ScillaIPCServer.cpp`
The Chain ID fetched is from the one stated in `constants.xml`

## Backward Compatibility

- [x] This is not a breaking change
- [ ] This is a breaking change

## Review Suggestion

## Status

### Implementation

- [x] **ready for review**

### Integration Test (Core Team)

- [x] local machine test

- [ ] small-scale cloud test

2022-02-09 09:08 UTC, sunny-teo9000 approved these changes
LGTM, just need to build scilla on jenkins, so that it can run this specific commit for the unit test.

2022-02-09 10:20 UTC, vaivaswatha approved these changes

2022-02-09 10:22 UTC, ansnunez requested changes

2022-02-09 10:22 UTC, ansnunez commented on src/libServer/ScillaIPCServer.cpp
> +  LOG_GENERAL(WARNING, "Invalid query_name");
Good improvement, but maybe display `query_name` itself so it's more useful

2022-02-10 02:34 UTC, ansnunez approved these changes

2022-02-10 02:35 UTC, merged