feat/ZIL-4688
Zilliqa/Zilliqa pull request #2890
Opened 2022-08-18 16:00 UTC by yaron-zilliqa

Most dependencies will be compiled by vcpkg automatically as part of manifest mode (a prerequisites is to install vcpkg, following the instruction at https://vcpkg.io/en/getting-started.html).

When configuring with CMake, the following has to be passed: -DCMAKE_TOOLCHAIN_FILE=<path-to-vcpkg>/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-linux-dynamic

When using build.sh, VCPKG_ROOT must be defined in the environment.

Dependencies are taken from the 2022.07.25 of vcpkg.

2022-08-26 14:34 UTC, CSideSteve requested changes
Can you add the nlohmann json package I mentioned and remove the nlohamnn json directory out of libUtils, I think this will improve compilation speed a little too.

2022-09-07 11:26 UTC, valeryz commented
I tried building it.  I love the cleannes!

Let's merge this. Might need to update the README and put the instructions from the description of this PR there.

2022-09-07 11:26 UTC, valeryz approved these changes

2022-09-12 04:10 UTC, closed without merging

2022-09-12 04:11 UTC, yaron-zilliqa commented
Had to reraise this (https://github.com/Zilliqa/Zilliqa/pull/2967) so the source branch is in this repo.