feat: move the process from Travis to Jenkins
Zilliqa/Zilliqa pull request #2903
Opened 2022-08-24 11:07 UTC by frankmeds

## Description

## Backward Compatibility

- [X] This is not a breaking change
- [ ] This is a breaking change

## Review Suggestion

## Status

### Implementation

- [X] **ready for review**

### Integration Test (Core Team)

- [ ] local machine test

- [ ] small-scale cloud test

2022-08-24 11:26 UTC, CSideSteve commented on scripts/ci_build.sh
> +    #./scripts/integration_test.sh || exit 1
Can we make a note somewhere that we are not linting right now and this should probably become a daily automated task on the repo an generating an email to appropriate team if non compliance detected

2022-08-24 11:27 UTC, CSideSteve approved these changes
LGTM - will need additional sanity tests in the future but good for now.

2022-08-24 12:06 UTC, n-hutton requested changes

2022-08-24 12:06 UTC, n-hutton commented on ci_script.sh
> +#scilla_container_id=$(docker container ls | grep scilla | awk '{print $1}')
delete?

2022-08-24 12:06 UTC, n-hutton commented on tests/Data/Test_Contract.cpp
> +    \"gas_remaining\": \"999999999\", \
do not merge, right?

2022-08-24 14:02 UTC, n-hutton approved these changes

2022-08-25 06:57 UTC, mauromedda approved these changes

2022-08-25 11:19 UTC, merged