Compress specific leveldb in persistence
Zilliqa/Zilliqa pull request #3052
Opened 2022-09-29 09:01 UTC by chetan-zilliqa

add missed cmake

comment update

## Description

same as #2843 
## Backward Compatibility

- [ ] This is not a breaking change
- [ ] This is a breaking change

## Review Suggestion

## Status

### Implementation

- [ ] **ready for review**

### Integration Test (Core Team)

- [ ] local machine test

- [ ] small-scale cloud test

2022-09-29 10:01 UTC, yaron-zilliqa requested changes
What's the point of this tool? is it really required at the moment?

2022-09-29 10:01 UTC, yaron-zilliqa commented on src/cmd/compress_persistence.cpp
> +    auto dbptr = std::make_shared<LevelDB>(dbname);
Why std::make_shared? std::make_unique is definitely preferable (and cheaper) in cases such as this.

2022-09-29 10:07 UTC, chetan-zilliqa commented
This was a tool initially written by Sandip to see if compression of level DB can reduce the persistence size. I added it as it's good to have for our reference.
https://github.com/Zilliqa/Zilliqa/pull/2732

2022-09-29 10:08 UTC, chetan-zilliqa commented
> What's the point of this tool? is it really required at the moment?

This was a tool initially written by Sandip to see if compression of level DB can reduce the persistence size. I added it as it's good to have for our reference.
https://github.com/Zilliqa/Zilliqa/pull/2732

2022-10-04 13:34 UTC, yaron-zilliqa requested changes

2022-10-04 13:34 UTC, yaron-zilliqa commented on src/cmd/compress_persistence.cpp
> +  string dbName;
No reason to be here; can just be inside the try.
Then you can consider changing:
```
int main(int argc, const char* argv[]) try {
  ...
  return static_cast<int>(STATUS::SUCCESS);
}
catch (std::exception& e) {
  ...
  return static_cast<int>(STATUS::ERROR_UNHANDLED_EXCEPTION);
}
```

2022-10-04 13:34 UTC, yaron-zilliqa commented on src/cmd/compress_persistence.cpp
> +enum class STATUS {
I think (as opposed to my previous comment), it'd be nicer to just make it a regular enum (i.e. remove the 'class').
This way we can skip the ugly explicit cast to ints below (static_cast<int>(...)).

2023-04-03 15:46 UTC, closed without merging