Zil-5586 : seedpubs  eth_getTransactionCount doesn't support pending block number
Zilliqa/Zilliqa pull request #3931
Opened 2024-04-17 05:04 UTC by chetan-zilliqa

## Description

## Backward Compatibility

- [ ] This is not a breaking change
- [ ] This is a breaking change

## Review Suggestion

## Status

### Implementation

- [ ] **ready for review**

### Integration Test (Core Team)

- [ ] local machine test

- [ ] small-scale cloud test

2024-04-17 08:26 UTC, DrZoltanFazekas requested changes

2024-04-17 08:26 UTC, DrZoltanFazekas commented on tests/EvmAcceptanceTests/test/EthTransactionCount.ts
> +            let receipt = await txn1.wait();
You have to move line 19-20 after line 22-23

2024-04-26 08:51 UTC, chetan-zilliqa commented on src/libData/AccountData/TransactionLite.h
> +  std::map<Address, std::vector<TransactionLite>> m_txnLiteMemPool;
Oh, yeah, correct. thanks for pointing.

2024-04-30 06:11 UTC, pavlops approved these changes

2024-04-30 06:13 UTC, merged